kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: jenkins-storage
provisioner: driver.longhorn.io
allowVolumeExpansion: true
reclaimPolicy: Retain
volumeBindingMode: Immediate
parameters:
  numberOfReplicas: "2"
  staleReplicaTimeout: "2880"
  fromBackup: ""
  # ext4 brings lost+found and non empty directory
  fsType: "xfs"
