version: '3.7'

services:
  opensearch:
    image: opensearchproject/opensearch:latest
    container_name: opensearch
    environment:
      - cluster.name=opensearch-cluster
      - node.name=opensearch-node
      - discovery.seed_hosts=opensearch-node
      - cluster.initial_master_nodes=opensearch-node
      - "OPENSEARCH_JAVA_OPTS=-Xms512m -Xmx512m"
      - bootstrap.memory_lock=true
      - "DISABLE_INSTALL_DEMO_CONFIG=true"
      - "DISABLE_SECURITY_PLUGIN=true"
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    volumes:
      - opensearch-data:/usr/share/opensearch/data
    ports:
      - 127.0.0.1:9200:9200
       # required for Performance Analyzer
      - 127.0.0.1:9600:9600
    # ensure it can start with global fluentd logging
    logging:
      driver: syslog
    labels:
    - "traefik.enable=true"
    - "traefik.http.routers.os.rule=Host(`os.${HOST_HOSTNAME}`)"
    restart: unless-stopped

  opensearch-dashboards:
    image: opensearchproject/opensearch-dashboards:latest
    container_name: opensearch-dashboards
    # ports:
    #   - 127.0.0.1:5601:5601
    # expose:
    #   - "5601"
    environment:
      - 'OPENSEARCH_HOSTS=["http://opensearch:9200"]'
      - "DISABLE_SECURITY_DASHBOARDS_PLUGIN=true"
    # ensure it can start with global fluentd logging
    logging:
      driver: syslog
    labels:
    - "traefik.enable=true"
    - "traefik.http.routers.os-dashboard.rule=Host(`os-dashboard.${HOST_HOSTNAME}`)"
    restart: unless-stopped

volumes:
  opensearch-data:

networks:
  default:
    name: devbox
    external: true

