apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: geonetwork
spec:
  rules:
  - host: geonetwork.dev.localhost
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: geonetwork
            port:
              number: 8080
