version: '3.5'

services:

  mailhog:
    container_name: mailhog
    image: mailhog/mailhog:latest
    ports:
    - 1025:1025
    labels:
    - "traefik.enable=true"
    - "traefik.http.routers.mailhog.rule=Host(`mailhog.${DEVBOX_HOSTNAME}`)"
    - "traefik.http.services.mailhog-service.loadbalancer.server.port=8025"
    restart: unless-stopped

networks:
  default:
    name: devbox
    external: true

