version: '3.8'

services:

  fluentd:
    build: .
    container_name: fluentd
    volumes:
      - ./conf:/fluentd/etc:ro
    ports:
      - "127.0.0.1:24224:24224"
      - "127.0.0.1:24224:24224/udp"
    # ensure it can start with global config
    logging:
      driver: syslog

networks:
  default:
    name: devbox
    external: true
