version: '3.8'

services:

  fluentd:
    build: .
    volumes:
      - ./conf:/fluentd/etc
    # links:
    #   - "elasticsearch"
    ports:
      - "127.0.0.1:24224:24224"
      - "127.0.0.1:24224:24224/udp"

networks:
  default:
    name: devbox
    external: true
