version: '3.5'

services:

  whoami:
    image: containous/whoami
    labels:
    - "traefik.enable=true"
    - "traefik.http.routers.whoami.rule=Host(`whoami.${HOST_HOSTNAME}`)"
    - "traefik.http.routers.whoami.tls=true"
    restart: unless-stopped

networks:
  default:
    name: devbox
    external: true
