version: "3"

services:
  loki:
    image: grafana/loki:2.9.2
    ports:
      - "3100:3100"
    command: -config.file=/etc/loki/local-config.yaml
    volumes:
    - loki-chunks:/loki/chunks
    - loki-rules:/loki/rules

  promtail:
    image: grafana/promtail:2.9.2
    volumes:
      - promtail-data:/data:rw
      - /var/log:/var/log:ro
      - /var/lib/docker/containers:/var/lib/docker/containers:ro
      - ./config/promtail-config.yaml:/etc/promtail/promtail-config.yaml:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
    command: -config.file=/etc/promtail/promtail-config.yaml -config.expand-env=true
    userns_mode: host

volumes:
  loki-chunks:
    name: loki-chunks
  loki-rules:
    name: loki-rules
  promtail-data:
    name: promtail-data

networks:
  default:
    name: devbox
    external: true
