version: '3.5'

services:

  postgis:
    container_name: postgis
    image: postgis:10.5-2.4
    build: .
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgis
      - POSTGRES_PASSWORD=postgis
    volumes:
      - postgis-data:/var/lib/postgresql/data
    restart: always

volumes:
  postgis-data:
    name: postgis-data

networks:
  default:
    external:
      name: webgateway
