version: '3'

services:

  postgis:
    container_name: postgis
    image: postgis/postgis:15-3.4
    ports:
      - "${DEVBOX_PORT_PREFIX}5432:5432"
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    volumes:
      - postgis-data:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  postgis-data:
    name: postgis-data-15

networks:
  default:
    name: devbox
    external: true
