version: '3.5'

services:

  postgis:
    container_name: postgis
    image: docker.pkg.github.com/mborne/docker-postgis/postgis:13.3-3.1
    build: https://github.com/mborne/docker-postgis.git#13.3-3.1
    ports:
      - "127.0.0.1:5432:5432"
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    volumes:
      - postgis-data:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  postgis-data:
    name: postgis-data-13

networks:
  default:
    name: devbox

