services:

  postgis:
    container_name: postgis
    image: ${POSTGIS_IMAGE}
    ports:
      - "${DEVBOX_PORT_PREFIX}5432:5432"
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    volumes:
      - postgis-data:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  postgis-data:
    name: postgis-data-17

networks:
  default:
    name: devbox
    external: true
