version: '3.5'

services:

  drupal:
    container_name: drupal
    image: drupal:8.8.4
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.drupal.rule=Host(`drupal.${HOST_HOSTNAME}`)"
    volumes:
      - drupal-modules:/var/www/html/modules
      - drupal-profiles:/var/www/html/profiles
      - drupal-sites:/var/www/html/sites
      - drupal-themes:/var/www/html/themes
    restart: unless-stopped

volumes:
  drupal-modules:
    name: drupal-modules
  drupal-profiles:
    name: drupal-profiles
  drupal-sites:
    name: drupal-sites
  drupal-themes:
    name: drupal-themes

networks:
  default:
    external:
      name: devbox
