version: '3.5'

services:
  seafile:
    image: seafileltd/seafile:6.3.4
    container_name: seafile
    restart: unless-stopped
    environment:
      - SEAFILE_SERVER_HOSTNAME=seafile.${HOST_HOSTNAME}
      - SEAFILE_ADMIN_EMAIL=${SEAFILE_ADMIN_EMAIL}
      - SEAFILE_ADMIN_PASSWORD=${SEAFILE_ADMIN_PASSWORD}
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.seafile.rule=Host(`seafile.${HOST_HOSTNAME}`)"
    volumes:
      - files:/shared

volumes:
  files:
    driver: local

networks:
  default:
    external:
      name: devbox

