version: '3.5'

services:

  registry:
    container_name: registry
    image: registry:2
    labels:
      - "traefik.enable=true"
      - "traefik.backend.port=5000"
      - "traefik.frontend.rule=Host:registry.localhost"
    volumes:
      - registry-data:/var/lib/registry
    restart: always

volumes:
  registry-data:
    name: registry-data

networks:
  default:
    external:
      name: webgateway

