apiVersion: elasticsearch.k8s.elastic.co/v1
kind: Elasticsearch
metadata:
  name: geonetwork
spec:
  # from https://github.com/geonetwork/core-geonetwork/tree/4.2.0/es#manual-installation
  version: 7.6.2
  nodeSets:
  - name: default
    count: 1
    config:
      node.store.allow_mmap: false
  http:
    tls:
      selfSignedCertificate:
        disabled: true
