# https://github.com/fluent/helm-charts/blob/main/charts/fluent-bit/values.yaml

daemonset:
  enabled: true

#-------------------------------------
# journald logs
#-------------------------------------
extraVolumes:
  - name: runlog
    hostPath:
      path: /run/log

extraVolumeMounts:
  - name: runlog
    mountPath: /run/log
    readOnly: true

config:
  ## https://docs.fluentbit.io/manual/pipeline/inputs
  inputs: |
    [INPUT]
        Name tail
        Path /var/log/containers/*.log
        multiline.parser cri
        Tag kube.*
        Mem_Buf_Limit 5MB
        Skip_Long_Lines On
    [INPUT]
        Name            systemd
        Tag             systemd.*
        Systemd_Filter  _SYSTEMD_UNIT=kubelet.service
        Systemd_Filter  _SYSTEMD_UNIT=containerd.service


  ## https://docs.fluentbit.io/manual/pipeline/filters
  filters: |
    [FILTER]
        Name                kubernetes
        Match               kube.*
        Merge_Log           On
        Keep_Log            Off
        Kube_Tag_Prefix     kube.var.log.containers.
        K8S-Logging.Parser  On
        K8S-Logging.Exclude On
    [FILTER]
        Name                nest
        Match               kube.*
        Wildcard            pod_name
        Operation           lift
        Nested_under        kubernetes
        Add_prefix          kubernetes_
    [FILTER]
        Name                modify
        Match               kube.*
        Copy                kubernetes_pod_name host

  outputs: |
    [OUTPUT]
        Name               opensearch
        Match              kube.*
        Host               opensearch-cluster.opensearch
        Port               9200
        Suppress_Type_Name On
        Logstash_Format    On
        Logstash_Prefix    devbox-containers
        Trace_Error        On
        Replace_Dots       On
        # HTTP_User        admin
        # HTTP_Passwd      admin
        # tls              On
        # tls.verify       Off
    [OUTPUT]
        Name               opensearch
        Match              systemd.*
        Host               opensearch-cluster.opensearch
        Port               9200
        Suppress_Type_Name On
        Logstash_Format    On
        Logstash_Prefix    devbox-systemd
        Trace_Error        On
        Replace_Dots       On
        # HTTP_User        admin
        # HTTP_Passwd      admin
        # tls              On
        # tls.verify       Off


tolerations:
  - key: node-role.kubernetes.io/master
    operator: Exists
    effect: NoSchedule
  - operator: "Exists"
    effect: "NoExecute"
  - operator: "Exists"
    effect: "NoSchedule"
