version: '3.5'

services:

  geonetwork:
    container_name: geonetwork
    image: geonetwork:4.2.0
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.geonetwork.rule=Host(`geonetwork.${HOST_HOSTNAME}`)"
      - "traefik.http.routers.geonetwork.tls=true"
    environment:
      - DATA_DIR=/var/lib/geonetwork_data
      - ES_HOST=es
    volumes:
      - geonetwork-data:/var/lib/geonetwork_data
    restart: unless-stopped

volumes:
  geonetwork-data:
    name: geonetwork-data

networks:
  default:
    name: devbox
    external: true
