apiVersion: v1
kind: PersistentVolume
metadata:
  name: postgis-pv
  labels:
    type: local
spec:
  storageClassName: postgis-storage
  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/var/devbox/postgis-13"
