# see https://docs.traefik.io/reference/static-configuration/file/
[providers.docker]
  exposedByDefault = false
  watch = true

[providers.file]
  # includes /etc/traefik/traefik.toml and other dynamic files
  directory = "/etc/traefik"
  watch = true

[entryPoints]
  [entryPoints.web]
    address = ":80"
  # redirect http to https
  #[entryPoints.web.http.redirections.entryPoint]
  #  to = "websecure"
  #  scheme = "https"
  [entryPoints.websecure]
    address = ":443"
  [entryPoints.websecure.http]
    tls = true

[http.middlewares]
  #-------------------------------------------------------------------
  # Middleware to redirect http to https
  #-------------------------------------------------------------------
  [http.middlewares.https-redirect.redirectscheme]
    scheme = "https"

[api]
  insecure = false
  dashboard = true
  debug = false

[pilot]
  dashboard = false

#-------------------------------------------------------------------
# Logs
#-------------------------------------------------------------------
[log]
  format = "json"
  
[accessLog]
  format = "json"
