version: '3.5'

services:

  kibana:
    container_name: kibana
    image: docker.elastic.co/kibana/kibana:8.3.2
    environment:
      - "SERVER_NAME=kibana.${DEVBOX_HOSTNAME}"
      - "ELASTICSEARCH_HOSTS=${ES_URL}"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.kibana.rule=Host(`kibana.${DEVBOX_HOSTNAME}`)"
      - "traefik.http.services.kibana-service.loadbalancer.server.port=5601"
    restart: unless-stopped

networks:
  default:
    name: devbox
    external: true
