version: '3.5'

services:

  kibana:
    container_name: kibana
    image: docker.elastic.co/kibana/kibana:7.15.2
    environment:
      - "SERVER_NAME=kibana.${HOST_HOSTNAME}"
      - "ELASTICSEARCH_HOSTS=${ES_URL}"
    ports:
      - "127.0.0.1:5601:5601"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.kibana.rule=Host(`kibana.${HOST_HOSTNAME}`)"
    restart: unless-stopped

networks:
  default:
    name: devbox
