version: '3.5'

services:

  geoserver:
    container_name: geoserver
    image: mborne/geoserver:2.16.1
    build:
      context: .
      args:
        version: '2.16.1'
    environment:
      - "CATALINA_OPTS=-Xms512m -Xmx512m"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.geoserver.rule=Host(`geoserver.${HOST_HOSTNAME}`)"
      - "traefik.http.routers.geoserver.middlewares=cors"
      - "traefik.http.middlewares.cors.headers.accesscontrolallowmethods=GET,PUT,POST,DELETE,OPTIONS,PUT"
      - "traefik.http.middlewares.cors.headers.accesscontrolalloworigin=*"
    volumes:
      - geoserver-data:/var/geoserver
    restart: unless-stopped

volumes:
  geoserver-data:
    name: geoserver-data

networks:
  default:
    external:
      name: devbox
