version: '3.5'

services:

  geoserver:
    container_name: geoserver
    image: mborne/geoserver:2.14.1
    build: .
    environment:
      - POSTGRES_USER=postgis
      - POSTGRES_PASSWORD=postgis
    labels:
      - "traefik.enable=true"
      - "traefik.backend.port=8080"
      - "traefik.frontend.rule=Host:geoserver.${HOST_HOSTNAME}"
    volumes:
      - geoserver-data:/var/geoserver
    restart: unless-stopped

volumes:
  geoserver-data:
    name: geoserver-data

networks:
  default:
    external:
      name: webgateway
