FROM tomcat:8.5

ARG version=2.13.1

ENV GEOSERVER_DATA_DIR=/var/geoserver

RUN wget -O /tmp/geoserver-war.zip http://sourceforge.net/projects/geoserver/files/GeoServer/${version}/geoserver-${version}-war.zip

#/usr/local/tomcat
