version: '3.5'

services:

  geoserver:
    container_name: geoserver
    image: geoserver:2.13.1
    build: .
    environment:
      - POSTGRES_USER=postgis
      - POSTGRES_PASSWORD=postgis
    labels:
      - "traefik.enable=true"
      - "traefik.backend.port=8080"
      - "traefik.frontend.rule=Host:geoserver.localhost"      
    volumes:
      - geoserver-data:/var/geoserver
    restart: always

volumes:
  geoserver-data:
    name: geoserver-data

networks:
  default:
    external:
      name: webgateway
