version: '3.5'

services:

  # https://github.com/osixia/docker-openldap
  openldap:
    container_name: openldap
    image: osixia/openldap:1.4.0
    environment:
      - LDAP_ORGANISATION=${LDAP_ORGANISATION}
      - LDAP_DOMAIN=${LDAP_DOMAIN}
      - LDAP_ADMIN_PASSWORD=${LDAP_ADMIN_PASSWORD}
      - LDAP_READONLY_USER=true
      - LDAP_READONLY_USER_USERNAME=readonly
      - LDAP_READONLY_USER_PASSWORD=${LDAP_READONLY_USER_PASSWORD}
    ports:
      - "${DEVBOX_PORT_PREFIX}389:389"
    volumes:
      - ldap-data:/var/lib/ldap
      - ldap-config:/etc/ldap/slapd.d
    restart: unless-stopped

  # https://github.com/osixia/docker-phpldapadmin
  ldapadmin:
    container_name: ldapadmin
    image: osixia/phpldapadmin:0.9.0
    environment:
      - PHPLDAPADMIN_LDAP_HOSTS=openldap
      - PHPLDAPADMIN_HTTPS=false
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.ldapadmin.rule=Host(`ldapadmin.${DEVBOX_HOSTNAME}`)"
    restart: unless-stopped

volumes:
  ldap-data:
    name: ldap-data
  ldap-config:
    name: ldap-config

networks:
  default:
    name: devbox
    external: true
