version: '3.5'

services:

  mailer:
    container_name: mailer
    image: namshi/smtp:latest
    ports:
      - "${DEVBOX_PORT_PREFIX}25:25"
    env_file:
      - config.env
    restart: unless-stopped

networks:
  default:
    name: devbox
    external: true
