podSecurityStandard: restricted
validationFailureAction: Audit

# TODO split with values-audit.yaml and values-enforce.yaml as follow :
#validationFailureAction: Enforce
#validationFailureActionOverrides:
#  all:
#    - action: audit
#      namespaces:
#        - loki
#        - fluent
#        - traefik
#        - nginx-system
