# see config discovery.type: single-node
singleNode: true

config:
  opensearch.yml: |
    cluster.name: opensearch-cluster

    # Bind to all interfaces because we don't know what IP address Docker will assign to us.
    network.host: 0.0.0.0

    # Setting network.host to a non-loopback address enables the annoying bootstrap checks. "Single-node" mode disables them again.
    # Implicitly done if ".singleNode" is set to "true".
    # discovery.type: single-node
    # https://stackoverflow.com/a/72789668/28740388
    # bootstrap.memory_lock: true


# note : default requests.memory < Xms512m is a bit strange...
resources:
  requests:
    cpu: "1000m"
    memory: "1024Mi"
  limits:
    #cpu: "8000m"
    memory: "1024Mi"

opensearchJavaOpts: "-Xmx512M -Xms512M"

securityContext:
  capabilities:
    drop:
      - ALL
  # readOnlyRootFilesystem: true
  allowPrivilegeEscalation: false
  runAsNonRoot: true
  runAsUser: 1000

persistence:
  enableInitChown: false

extraEnvs:
  # - name: OPENSEARCH_INITIAL_ADMIN_PASSWORD
  #   value: 'ItWouldB3CoolToGenerateThis!'
  - name: DISABLE_INSTALL_DEMO_CONFIG
    value: 'true'
  - name: DISABLE_SECURITY_PLUGIN
    value: 'true'
