apiVersion: 1
datasources:
- name: Prometheus
  uid: prometheus
  type: prometheus
  url: http://prometheus:9090
  access: proxy
  isDefault: true
- name: Loki
  uid: loki
  type: loki
  url: http://loki:3100
  access: proxy
  isDefault: false
  editable: true
