version: '3.5'

services:

  server:
    container_name: nfs_server
    image: registry.k8s.io/volume-nfs:0.8
    privileged: true
    volumes:
      - nfs-data:/exports
    restart: unless-stopped

volumes:
  nfs-data:
    name: nfs-data

networks:
  default:
    name: devbox
    external: true
