version: '3.5'

services:

  keycloak:
    container_name: keycloak
    image: quay.io/keycloak/keycloak:20.0
    # see https://www.keycloak.org/server/reverseproxy
    command: start --proxy edge
    depends_on:
      - "db"
    environment:
      - KC_HOSTNAME=keycloak.${DEVBOX_HOSTNAME}
      - KEYCLOAK_ADMIN=${KEYCLOAK_ADMIN}
      - KEYCLOAK_ADMIN_PASSWORD=${KEYCLOAK_ADMIN_PASSWORD}
      - KC_DB=postgres
      - KC_DB_URL=jdbc:postgresql://db/keycloak
      - KC_DB_USERNAME=keycloak
      - KC_DB_PASSWORD=${POSTGRES_PASSWORD}
      - KEYCLOAK_WELCOME_THEME=custom
      - KEYCLOAK_DEFAULT_THEME=keycloak
      - PROXY_ADDRESS_FORWARDING=true
    # volumes:
    #   - keycloak-data:/opt/jboss/keycloak/standalone
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.keycloak.rule=Host(`keycloak.${DEVBOX_HOSTNAME}`)"
      - "traefik.http.services.keycloak-service.loadbalancer.server.port=8080"
    restart: unless-stopped

  db:
    container_name: keycloak_db
    image: postgres:13
    environment:
      - POSTGRES_USER=keycloak
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    volumes:
      - keycloak-db-data:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  keycloak-data:
    name: keycloak-data
  keycloak-db-data:
    name: keycloak-db-data

networks:
  default:
    name: devbox
    external: true


