version: '3.5'

services:

  keycloak:
    container_name: keycloak
    image: jboss/keycloak:13.0.1
    environment:
      - DB_VENDOR=postgres
      - DB_DATABASE=keycloak
      - DB_ADDR=postgis
      - DB_USER=${POSTGRES_USER}
      - DB_PASSWORD=${POSTGRES_PASSWORD}
      - KEYCLOAK_WELCOME_THEME=custom
      - KEYCLOAK_DEFAULT_THEME=keycloak
    volumes:
      - keycloak-data:/opt/jboss/keycloak/standalone
      - ./custom-theme:/opt/jboss/keycloak/themes/custom:ro
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.keycloak.rule=Host(`keycloak.${HOST_HOSTNAME}`)"
    restart: unless-stopped

volumes:
  keycloak-data:
    name: keycloak-data

networks:
  default:
    name: devbox


