version: '3.5'

services:

  keycloak:
    container_name: keycloak
    image: jboss/keycloak:6.0.1
    environment:
      - KEYCLOAK_USER=${KEYCLOAK_USER}
      - KEYCLOAK_PASSWORD=${KEYCLOAK_PASSWORD}
      - DB_VENDOR=postgres
      - DB_ADDR=postgis
      - DB_USER=postgis
      - DB_PASSWORD=postgis
    labels:
      - "traefik.enable=true"
      - "traefik.backend.port=8080"
      - "traefik.frontend.rule=Host:keycloak.${HOST_HOSTNAME}"
    restart: unless-stopped

volumes:
  keycloak-data:
    name: keycloak-data

networks:
  default:
    external:
      name: webgateway



