{
 "title": "My Kubernetes Nodes",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Informations générales",
   "type": "table",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 0 },
   "targets": [
    { "expr": "kube_node_info", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Pods par noeud",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 5 },
   "targets": [
    {
     "expr": "sum by (node) ( kube_pod_info )",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Pods par namespace",
   "type": "piechart",
   "gridPos": { "h": 12, "w": 8, "x": 0, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (namespace) ( kube_pod_info )",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Panel Title",
   "type": "table",
   "gridPos": { "h": 12, "w": 16, "x": 8, "y": 10 },
   "targets": [
    {
     "expr": "sum by (namespace) ( kube_pod_info )",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}