services:
  mailpit:
    image: axllent/mailpit:latest
    container_name: mailpit
    ports:
      - "${DEVBOX_PORT_PREFIX}1025:1025"    # SMTP
    volumes:
      - mailpit-data:/data
    # expose mailpit on http://mailpit.dev.locahost with traefik
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.mailpit.rule=Host(`mailpit.${DEVBOX_HOSTNAME}`)"
      - "traefik.http.routers.mailpit.entrypoints=web"
      - "traefik.http.services.mailpit.loadbalancer.server.port=8025"
    restart: unless-stopped

volumes:
  mailpit-data:
    name: mailpit-data

networks:
  default:
    name: devbox
    external: true
