version: '3.5'

services:

  traefik:
    container_name: traefik
    image: traefik:v2.4
    # Enables the web UI and tells Traefik to listen to docker
    ports:
      - "127.0.0.1:80:80"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.traefik.rule=Host(`traefik.${HOST_HOSTNAME}`)"
      - "traefik.http.services.traefik-service.loadbalancer.server.port=8080"
    volumes:
      - ./traefik.toml:/etc/traefik/traefik.toml:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
    restart: unless-stopped

networks:
  default:
    name: devbox
