version: '3.5'

services:

  traefik:
    container_name: traefik
    image: traefik:1.6
    ports:
      - "80:80"
      - "8888:8080"
    volumes:
      - ./traefik.toml:/etc/traefik/traefik.toml:ro
      - /var/run/docker.sock:/var/run/docker.sock
    restart: always

networks:
  default:
    external:
      name: webgateway
