version: '3.5'

services:

  traefik:
    container_name: traefik
    image: traefik:v2.8
    ports:
      - "127.0.0.1:80:80"
      - "127.0.0.1:443:443"
    volumes:
      - ./certs:/certs:ro
      - ./traefik.toml:/etc/traefik/traefik.toml:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
    userns_mode: 'host'
    privileged: true
    restart: unless-stopped

networks:
  default:
    name: devbox
