version: '3.7'

services:

  traefik:
    container_name: traefik
    image: traefik:v2.8
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./certs:/certs:ro
      - ./config:/etc/traefik:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
    # permission on /var/run/docker.sock
    userns_mode: 'host'
    # removes contraint to share network with traefik?
    network_mode: 'host'
    privileged: true
    restart: unless-stopped

