# see https://docs.traefik.io/reference/static-configuration/file/
[providers.docker]
  exposedByDefault = false
  watch = true

[providers.file]
  filename = "/etc/traefik/traefik.toml"

[http.middlewares]
  [http.middlewares.cors.headers]
    accessControlAllowMethods= ["GET", "OPTIONS", "PUT", "POST", "DELETE"]
    accessControlAllowOrigin = "*"

[api]
  insecure = true

[accessLog]

