services:

  grafana:
    container_name: grafana
    image: grafana/grafana:main
    environment:
    - GF_SECURITY_ADMIN_USER=admin
    - GF_SECURITY_ADMIN_PASSWORD=${GRAFANA_ADMIN_PASSWORD}
    - HTTP_PROXY=${HTTP_PROXY:-}
    - HTTPS_PROXY=${HTTPS_PROXY:-}
    - NO_PROXY="prometheus,loki,${NO_PROXY:-}"
    volumes:
      - grafana-data:/var/lib/grafana
      - ./config/datasources:/etc/grafana/provisioning/datasources:ro
      - ./config/dashboards:/etc/grafana/provisioning/dashboards:ro
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.grafana.rule=Host(`grafana.${DEVBOX_HOSTNAME}`)"
      - "traefik.http.services.grafana-service.loadbalancer.server.port=3000"
    restart: 'unless-stopped'

volumes:
  grafana-data:
    name: grafana-data

networks:
  default:
    name: devbox
    external: true
