version: '3.6'

services:

  grafana:
    container_name: grafana
    image: grafana/grafana:main
    entrypoint:
      - sh
      - -euc
      - |
        mkdir -p /etc/grafana/provisioning/datasources
        cat <<EOF > /etc/grafana/provisioning/datasources/ds.yaml
        apiVersion: 1
        datasources:
        - name: Prometheus
          type: prometheus
          access: proxy
          orgId: 1
          url: http://prometheus:9090
          basicAuth: false
          isDefault: true
          version: 1
          editable: true
        - name: Loki
          type: loki
          access: proxy
          orgId: 1
          url: http://loki:3100
          basicAuth: false
          isDefault: false
          version: 1
          editable: true
        EOF
        /run.sh
    environment:
    - HTTP_PROXY=${HTTP_PROXY}
    - HTTPS_PROXY=${HTTPS_PROXY}
    - NO_PROXY="prometheus,${NO_PROXY}"
    volumes:
      - grafana-data:/var/lib/grafana
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.grafana.rule=Host(`grafana.${DEVBOX_HOSTNAME}`)"
      - "traefik.http.services.grafana-service.loadbalancer.server.port=3000"
    restart: 'unless-stopped'

volumes:
  grafana-data:
    name: grafana-data

networks:
  default:
    name: devbox
    external: true
