apiVersion: v1
kind: ConfigMap
metadata:
  name: traefik-config-static
data:
  traefik.yml: |
    entryPoints:
      web:
        address: :80
        http:{}
        # http:
        #   redirections:
        #     entryPoint:
        #       to: websecure
        #       scheme: https
      websecure:
        address: ':443'
        http:
          tls: {}

    providers:
      kubernetesCRD: {}
      kubernetesIngress: {}

    pilot:
      enabled: false

    api:
      dashboard: true

    # https://doc.traefik.io/traefik/observability/logs/#logs
    log:
      level: INFO
