kind: DaemonSet
apiVersion: apps/v1
metadata:
  name: traefik
spec:
  template:
    spec:
      serviceAccountName: traefik-ingress-controller
      terminationGracePeriodSeconds: 60
      containers:
        - image: traefik:v2.7
          name: traefik-ingress-lb
          ports:
            - name: http
              containerPort: 80
              hostPort: 80
            - name: https
              containerPort: 443
              hostPort: 443
          securityContext:
            capabilities:
              drop:
                - ALL
              add:
                - NET_BIND_SERVICE
          volumeMounts:
            - name: traefik-config-static
              mountPath: /etc/traefik/
      volumes:
        - name: traefik-config-static
          configMap:
            name: traefik-config-static
