apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

commonLabels:
  app: traefik

# https://github.com/traefik/traefik/tree/v2.7/docs/content/reference/dynamic-configuration
resources:
  # traefik CRD
  #- https://raw.githubusercontent.com/traefik/traefik/v2.7/docs/content/reference/dynamic-configuration/kubernetes-crd-definition-v1.yml
  - https://raw.githubusercontent.com/traefik/traefik/v2.7/docs/content/reference/dynamic-configuration/traefik.containo.us_ingressroutes.yaml
  - https://raw.githubusercontent.com/traefik/traefik/v2.7/docs/content/reference/dynamic-configuration/traefik.containo.us_ingressroutetcps.yaml
  - https://raw.githubusercontent.com/traefik/traefik/v2.7/docs/content/reference/dynamic-configuration/traefik.containo.us_ingressrouteudps.yaml
  - https://raw.githubusercontent.com/traefik/traefik/v2.7/docs/content/reference/dynamic-configuration/traefik.containo.us_middlewares.yaml
  - https://raw.githubusercontent.com/traefik/traefik/v2.7/docs/content/reference/dynamic-configuration/traefik.containo.us_middlewaretcps.yaml
  - https://raw.githubusercontent.com/traefik/traefik/v2.7/docs/content/reference/dynamic-configuration/traefik.containo.us_serverstransports.yaml
  - https://raw.githubusercontent.com/traefik/traefik/v2.7/docs/content/reference/dynamic-configuration/traefik.containo.us_tlsoptions.yaml
  - https://raw.githubusercontent.com/traefik/traefik/v2.7/docs/content/reference/dynamic-configuration/traefik.containo.us_tlsstores.yaml
  - https://raw.githubusercontent.com/traefik/traefik/v2.7/docs/content/reference/dynamic-configuration/traefik.containo.us_traefikservices.yaml

  # RBAC
  - https://raw.githubusercontent.com/traefik/traefik/v2.7/docs/content/reference/dynamic-configuration/kubernetes-crd-rbac.yml
  - service-account.yaml

  - config-map.yaml
  - daemon-set.yaml

  - middleware-ipwhitelist.yaml

  - ingress-dashboard.yaml

