apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: kube-system

commonLabels:
  app: traefik

resources:
  # - "https://raw.githubusercontent.com/traefik/traefik/v2.7/docs/content/reference/dynamic-configuration/kubernetes-crd-definition-v1.yml"
  - namespace.yaml
  - definition-v1.yaml
  - service-account.yaml
  - rbac.yaml
  - daemon-set.yaml
