version: '3.8'

services:

  fluentd:
    build: .
    container_name: fluentd
    volumes:
      - ./conf:/fluentd/etc:ro
      - /var/log:/var/log:ro
    ports:
      - "127.0.0.1:24224:24224"
      - "127.0.0.1:24224:24224/udp"
    userns_mode: 'host'
    privileged: true
    # ensure it can start with global fluentd logging
    logging:
      driver: syslog
    restart: unless-stopped

networks:
  default:
    name: devbox
    external: true
