daemonset:
  enabled: true

config:
  ## https://docs.fluentbit.io/manual/pipeline/inputs
  inputs: |
    [INPUT]
        Name tail
        Path /var/log/containers/*.log
        multiline.parser cri
        Tag kube.*
        Mem_Buf_Limit 5MB
        Skip_Long_Lines On

    # [INPUT]
    #     Name systemd
    #     Tag host.*
    #     Systemd_Filter _SYSTEMD_UNIT=kubelet.service
    #     Read_From_Tail On

  ## https://docs.fluentbit.io/manual/pipeline/filters
  filters: |
    [FILTER]
        Name                kubernetes
        Match               kube.*
        Merge_Log           On
        Keep_Log            Off
        Kube_Tag_Prefix     kube.var.log.containers.
        K8S-Logging.Parser  On
        K8S-Logging.Exclude On
    [FILTER]
        Name                nest
        Match               kube.*
        Wildcard            pod_name
        Operation           lift
        Nested_under        kubernetes
        Add_prefix          kubernetes_
    [FILTER]
        Name                modify
        Match               kube.*
        Copy                kubernetes_pod_name host
    [FILTER]
        Name                modify
        Match               kube.*
        Rename              message short_message
    [FILTER]
        Name                modify
        Match               kube.*
        Add     log         "none"

  outputs: |
    [OUTPUT]
        Name               opensearch
        Match              kube.*
        Host               opensearch-cluster-master.opensearch
        Port               9200
        Suppress_Type_Name On
        Logstash_Format    On
        Logstash_Prefix    logstash
        HTTP_User          admin
        HTTP_Passwd        admin
        tls                On
        tls.verify         Off


tolerations:
  - key: node-role.kubernetes.io/master
    operator: Exists
    effect: NoSchedule
  - operator: "Exists"
    effect: "NoExecute"
  - operator: "Exists"
    effect: "NoSchedule"

# volumeMounts:
# - name: varlog
#   mountPath: /var/log
# - name: varlibdockercontainers
#   mountPath: /var/lib/docker/containers
#   readOnly: true
# - name: fluent-bit-config
#   mountPath: /fluent-bit/etc/
# terminationGracePeriodSeconds: 10
# volumes:
# - name: varlog
# hostPath:
#   path: /var/log
# - name: varlibdockercontainers
# hostPath:
#   path: /var/lib/docker/containers
# - name: fluent-bit-config
# configMap:
#   name: fluent-bit-config
# serviceAccountName: fluent-bit
