version: '3.5'

services:
  nextcloud:
    image: nextcloud:stable
    container_name: nextcloud
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.nextcloud.rule=Host(`nextcloud.${DEVBOX_HOSTNAME}`)"
    volumes:
      - files:/var/www/html

volumes:
  files:
    driver: local

networks:
  default:
    name: devbox
    external: true
