# see https://docs.traefik.io/reference/static-configuration/file/
[providers.docker]
  exposedByDefault = false
  watch = true

[providers.file]
  # includes /etc/traefik/traefik.toml and other dynamic files
  directory = "/etc/traefik"
  watch = true

#-------------------------------------------------------------------
# Configure SSL certificates
#-------------------------------------------------------------------
[[tls.certificates]]
    certFile = "/certs/default.pem"
    keyFile  = "/certs/default-key.pem"

[entryPoints]
  [entryPoints.web]
    address = ":80"
  # redirect http to https
  [entryPoints.web.http.redirections.entryPoint]
    to = "websecure"
    scheme = "https"
  [entryPoints.websecure]
    address = ":443"
  [entryPoints.websecure.http]
    tls = true

[http.middlewares]
  #-------------------------------------------------------------------
  # Middleware to redirect http to https
  #-------------------------------------------------------------------
  [http.middlewares.https-redirect.redirectscheme]
    scheme = "https"

  #-------------------------------------------------------------------
  # Middleware to filter by IP
  #-------------------------------------------------------------------
  [http.middlewares.whitelist.ipWhiteList]
    sourceRange = ["127.0.0.0/8", "192.168.0.0/16", "172.80.0.0/16", "172.90.0.0/16", "172.17.0.0/16", "10.0.0.0/8"]

  #-------------------------------------------------------------------
  # Middleware to add cors headers
  #-------------------------------------------------------------------
  [http.middlewares.cors.headers]
    accessControlAllowMethods= ["GET", "OPTIONS", "PUT", "POST", "DELETE"]
    accessControlAllowOriginList = "*"

  #-------------------------------------------------------------------
  # Middleware to add security headers
  # (see https://securityheaders.com/)
  #-------------------------------------------------------------------
  [http.middlewares.security-headers.headers]
    [http.middlewares.security-headers.headers.customResponseHeaders]
      # traefik pilot
      #X-Frame-Options = "SAMEORIGIN"
      Strict-Transport-Security = 'max-age=31536000;'
      X-Content-Type-Options = "nosniff"
      Referrer-Policy = "strict-origin"

#-------------------------------------------------------------------
# API and dashboard
#-------------------------------------------------------------------
[http.routers.traefik]
  rule = "Host(`traefik.dev.localhost`)"
  service = "api@internal"

[api]
  insecure = false
  dashboard = true
  debug = false

[pilot]
  dashboard = false

#-------------------------------------------------------------------
# Logs
#-------------------------------------------------------------------
[log]
  format = "json"
  
[accessLog]
  format = "json"
