version: '3.5'

services:

  rabbitmq:
    container_name: rabbitmq
    image: rabbitmq:3-management
    environment:
      - RABBITMQ_DEFAULT_USER=${RABBITMQ_USER}
      - RABBITMQ_DEFAULT_PASS=${RABBITMQ_PASS}
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.rabbitmq.rule=Host(`rabbitmq.${HOST_HOSTNAME}`)"
      - "traefik.http.services.rabbitmq-service.loadbalancer.server.port=15672"
    restart: unless-stopped

networks:
  default:
    external:
      name: devbox

