version: '3.5'

services:

  es:
    container_name: es
    image: docker.elastic.co/elasticsearch/elasticsearch:8.3.2
    environment:
      - node.name=es
      - cluster.name=es-docker-single
      - discovery.type=single-node
      - xpack.security.enabled=false
      - "ES_JAVA_OPTS=${ES_JAVA_OPTS}"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports:
      - "${DEVBOX_PORT_PREFIX}9200:9200"
      - "${DEVBOX_PORT_PREFIX}9300:9300"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.es.rule=Host(`es.${DEVBOX_HOSTNAME}`)"
      - "traefik.http.services.es-service.loadbalancer.server.port=9200"
    volumes:
      - es-data:/usr/share/elasticsearch/data
    restart: unless-stopped

volumes:
  es-data:
    name: es-data

networks:
  default:
    name: devbox
    external: true
