apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: adminer

commonLabels:
  app: adminer

resources:
  - namespace.yaml
  - service.yaml
  - deployment.yaml
  - ingress.yaml

