version: '3.5'

services:

  adminer:
    container_name: adminer
    image: adminer:latest
    environment:
    - ADMINER_DESIGN=nette
    labels:
    - "traefik.enable=true"
    - "traefik.http.routers.adminer.rule=Host(`adminer.${DEVBOX_HOSTNAME}`)"
    - "traefik.http.services.adminer-service.loadbalancer.server.port=8080"
    restart: unless-stopped

networks:
  default:
    name: devbox
    external: true

