version: '3.5'

services:

  traefik:
    container_name: traefik
    image: traefik:1.7
    ports:
      - "80:80"
      - "443:443"
      - "8888:8080"
    volumes:
      - ./traefik.toml:/etc/traefik/traefik.toml:ro
      - /var/run/docker.sock:/var/run/docker.sock
      - ./acme.json:/acme.json
    restart: unless-stopped

networks:
  default:
    external:
      name: webgateway
