#------------------------------------------------------------------------------------------
# helm values to generate LetsEncrypt certificates using HTTP-01 
# challenge (https://letsencrypt.org/docs/challenge-types/#http-01-challenge)
#  
# see https://github.com/traefik/traefik-helm-chart/blob/master/traefik/values.yaml
#------------------------------------------------------------------------------------------

deployment:
  initContainers:
    # The "volume-permissions" init container is required if you run into permission issues.
    # Related issue: https://github.com/containous/traefik/issues/6972
    - name: volume-permissions
      image: busybox:1.31.1
      command: ["sh", "-c", "chmod -Rv 600 /data/*"]
      volumeMounts:
        - name: data
          mountPath: /data

# Enable persistence using Persistent Volume Claims to persist TLS certificates.
persistence:
  enabled: true
  name: data
  #  existingClaim: ""
  accessMode: ReadWriteOnce
  size: 128Mi
  # storageClass: ""
  path: /data
  annotations: {}
  # subPath: "" # only mount a subpath of the Volume into the pod

certResolvers:
  letsencrypt:
    # for challenge options cf. https://doc.traefik.io/traefik/https/acme/
    email: admin@quadtreeworld.net
    tlsChallenge: true
    httpChallenge:
      entryPoint: "web"
    # match the path to persistence
    storage: /data/acme.json
