admissionController:
  replicas: 3
  metricsService:
    create: true
    annotations:
      prometheus.io/port: "8000"
      prometheus.io/scrape: "true"

backgroundController:
  replicas: 2
cleanupController:
  replicas: 2
reportsController:
  replicas: 2
