admissionController:
  replicas: 3
  metricsService:
    create: true
    annotations:
      prometheus.io/port: "8000"
      prometheus.io/scrape: "true"

backgroundController:
  replicas: 2
cleanupController:
  replicas: 2
reportsController:
  replicas: 2

config:
  webhooks:
    - namespaceSelector:
        matchExpressions:
        - key: kubernetes.io/metadata.name
          operator: NotIn
          values:
            - kube-system
            - kube-public
            - kube-node-lease
