version: '3'

services:
  db:
    image: postgres:11.9-alpine
    environment:
      PGDATA: /var/lib/postgresql/data/pgdata
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    restart: unless-stopped
    volumes:
      - db_data:/var/lib/postgresql/data

  fusionauth:
    image: fusionauth/fusionauth-app:1.27.2
    depends_on:
      - db
    environment:
      DATABASE_URL: jdbc:postgresql://db:5432/fusionauth
      DATABASE_ROOT_USERNAME: ${POSTGRES_USER}
      DATABASE_ROOT_PASSWORD: ${POSTGRES_PASSWORD}
      DATABASE_USERNAME: ${DATABASE_USERNAME}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD}
      FUSIONAUTH_APP_MEMORY: ${FUSIONAUTH_APP_MEMORY}
      FUSIONAUTH_APP_RUNTIME_MODE: development
      FUSIONAUTH_APP_URL: http://fusionauth.${HOST_HOSTNAME}
      SEARCH_TYPE: database

    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.fusionauth.rule=Host(`fusionauth.${HOST_HOSTNAME}`)"
    ports:
      - "127.0.0.1:9011:9011"
    volumes:
      - fa_config:/usr/local/fusionauth/config

volumes:
  db_data:
  fa_config:


networks:
  default:
    name: devbox
