http:
  middlewares:
    whitelist:
      ipWhiteList:
        sourceRange:
        - "127.0.0.0/8"
        - "192.168.0.0/16"
        - "172.80.0.0/16"
        - "172.90.0.0/16"
        - "172.17.0.0/16"
        - "10.0.0.0/8"

