kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: traefik-ingress-controller
rules:
- apiGroups: [""]
  resources: ["services"]
  verbs: ["get","list","watch"]
- apiGroups: [""]
  resources: ["endpoints"]
  verbs: ["get","list","watch"]
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["get","list","watch"]
- apiGroups: [""]
  resources: ["ingresses/status"]
  verbs: ["update"]
