apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: kube-system

commonLabels:
  app: traefik

resources:
  - cluster-role.yaml
  - cluster-role-binding.yaml
  - service-account.yaml
  - daemon-set.yaml
