apiVersion: v1
kind: PersistentVolume
metadata:
  name: jenkins-pv
  labels:
    type: local
spec:
  storageClassName: jenkins-storage
  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteOnce
  #persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: "/var/devbox/jenkins-data/"
