---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: whoami
spec:
  replicas: 5
  selector:
    matchLabels:
      app: whoami
  template:
    metadata:
      labels:
        app: whoami
    spec:
      containers:
        - name: whoami
          image: traefik/whoami:v1.9
          ports:
            - containerPort: 80
