version: '3.5'

services:

  jenkins:
    container_name: jenkins
    image: mborne/jenkins:lts
    build: https://github.com/mborne/docker-jenkins.git
    environment:
      - TZ=Europe/Paris
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.jenkins.rule=Host(`jenkins.${HOST_HOSTNAME}`)"
    volumes:
      - jenkins-data:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
    restart: unless-stopped

volumes:
  jenkins-data:
    name: jenkins-data

networks:
  default:
    name: devbox
