version: '3.5'

services:

  jenkins:
    container_name: jenkins
    image: jenkins/jenkins:lts
    ports:
      - "50000:50000"
    labels:
      - "traefik.enable=true"
      - "traefik.backend.port=8080"
      - "traefik.frontend.rule=Host:jenkins.${HOST_HOSTNAME}"
    volumes:
      - jenkins-data:/var/jenkins_home
    restart: always

volumes:
  jenkins-data:
    name: jenkins-data

networks:
  default:
    external:
      name: webgateway
