version: '3.5'

services:

  jenkins:
    container_name: jenkins
    image: jenkins/jenkins:lts
    environment:
      - TZ=Europe/Paris
    labels:
      - "traefik.http.routers.jenkins.rule=Host(`jenkins.${HOST_HOSTNAME}`)"
    volumes:
      - jenkins-data:/var/jenkins_home
    restart: unless-stopped

volumes:
  jenkins-data:
    name: jenkins-data

networks:
  default:
    external:
      name: webgateway
