version: '3.6'

services:

  vault:
    container_name: vault
    image: vault:1.11.0
    command: server
    volumes:
      #- ./config.json:/vault/config/local.json
      - vault-file:/vault/file
      - vault-logs:/vault/logs
    ports:
      - "127.0.0.1:8200:8200"
    labels:
    - "traefik.enable=true"
    - "traefik.http.routers.vault.rule=Host(`vault.${HOST_HOSTNAME}`)"
    - "traefik.http.services.vault-service.loadbalancer.server.port=8200"
    cap_add:
    - IPC_LOCK


volumes:
  vault-file:
    name: vault-file
  vault-logs:
    name: vault-logs

networks:
  default:
    name: devbox
