apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: jenkins

commonLabels:
  app: jenkins

resources:
  - namespace.yaml
  - service.yaml
  - statefulset.yaml
  - ingress.yaml
  - rbac.yaml
