version: '3.5'

services:

  #-----------------------------------------------------------------------------
  # elasticsearch
  #-----------------------------------------------------------------------------
  elasticsearch:
    container_name: elasticsearch
    image: docker.elastic.co/elasticsearch/elasticsearch:6.3.0
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      - discovery.type=single-node
    labels:
      - "traefik.enable=true"
      - "traefik.backend.port=9200"
      - "traefik.frontend.rule=Host:es.${HOST_HOSTNAME}"
    volumes:
      - es-data:/usr/share/elasticsearch/data
    restart: always

  #-----------------------------------------------------------------------------
  # kibana
  #-----------------------------------------------------------------------------
  kibana:
    container_name: kibana
    image: docker.elastic.co/kibana/kibana:6.3.0
    ports:
      - "5601:5601"
    depends_on:
      - elasticsearch
    environment:
      SERVER_NAME: kibana.docker
      ELASTICSEARCH_URL: http://elasticsearch:9200
    labels:
      - "traefik.enable=true"
      - "traefik.backend.port=9200"
      - "traefik.frontend.rule=Host:kibana.${HOST_HOSTNAME}"
    restart: always

volumes:
  es-data:
    name: es-data

networks:
  default:
    external:
      name: webgateway
