server:
  persistentVolume:
    size: 20Gi
    # Default: "15d"
    retention: "7d"

# using grafana
alertmanager:
  enabled: false

# replace instance=NODE_IP:NODE_PORT by instance=NODE_NAME
# see https://github.com/prometheus-community/helm-charts/tree/main/charts/prometheus-node-exporter
# prometheus-node-exporter:
#   prometheus:
#     relabelings:
#       - action: replace
#         regex: (.*)
#         replacement: $1
#         sourceLabels: [__meta_kubernetes_pod_node_name]
#         targetLabel: instance


# relabel_configs:
#   .....
#   # relable the label 'instance' with your pod_node_name 
#   - source_labels: [__meta_kubernetes_pod_node_name]
#     target_label: instance

# extraScrapeConfigs:
#   - job_name: 'prometheus-blackbox-exporter'
#     metrics_path: /probe
#     params:
#       module: [http_2xx]
#     static_configs:
#       - targets:
#         - https://example.com
#     relabel_configs:
#       - source_labels: [__address__]
#         target_label: __param_target
#       - source_labels: [__param_target]
#         target_label: instance
#       - target_label: __address__
#         replacement: prometheus-blackbox-exporter:9115
