version: '3.5'

services:

  portainer:
    container_name: portainer
    image: portainer/portainer:latest
    labels:
      - "traefik.enable=true"
      - "traefik.backend.port=9000"
      - "traefik.frontend.rule=Host:portainer.${HOST_HOSTNAME}"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    restart: always

volumes:
  portainer-data:
    name: portainer-data

networks:
  default:
    external:
      name: webgateway

