version: '3.5'

services:

  portainer:
    container_name: portainer
    image: portainer/portainer:latest
    labels:
      - "traefik.http.routers.portainer.rule=Host(`portainer.${HOST_HOSTNAME}`)"
    volumes:
      - portainer-data:/data
      - /var/run/docker.sock:/var/run/docker.sock
    restart: unless-stopped

volumes:
  portainer-data:
    name: portainer-data

networks:
  default:
    external:
      name: webgateway

