services:

  matomo:
    image: matomo:5.7.1
    container_name: matomo
    depends_on:
      db:
        condition: service_healthy
    read_only: true
    volumes:
      - matomo-data:/var/www/html
      - matomo-var-run:/var/run
      - ./scripts:/scripts
    environment:
      MATOMO_DATABASE_HOST: db:3306
      MATOMO_DATABASE_USERNAME: ${MATOMO_DATABASE_USERNAME}
      MATOMO_DATABASE_PASSWORD: ${MATOMO_DATABASE_PASSWORD}
      MATOMO_DATABASE_DBNAME: matomo
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.matomo.rule=Host(`matomo.${DEVBOX_HOSTNAME}`)"
    restart: unless-stopped

  db:
    container_name: matomo_db
    image: mysql:8.4
    volumes:
      - db-data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${MATOMO_DATABASE_PASSWORD}
      MYSQL_DATABASE: matomo
      MYSQL_USER: ${MATOMO_DATABASE_USERNAME}
      MYSQL_PASSWORD: ${MATOMO_DATABASE_PASSWORD}
    healthcheck:
        test: "mysqladmin ping -h localhost --user=$$MYSQL_USER --password=$$MYSQL_PASSWORD"
        start_period: 1s
        interval: 5s
        timeout: 3s
        retries: 50
    restart: unless-stopped

  demo:
    container_name: matomo_demo
    image: nginx:latest
    volumes:
      - ./demo-matomo/public:/usr/share/nginx/html:ro
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.demo-matomo.rule=Host(`demo-matomo.${DEVBOX_HOSTNAME}`)"
    restart: unless-stopped

volumes:
  matomo-data:
    name: matomo-data
  matomo-var-run:
    name: matomo-var-run
  db-data:
    name: matomo-db-data

networks:
  default:
    name: devbox
    external: true



