persistence:
  enabled: true

sidecar:
  dashboards:
    enabled: true
  datasources:
    enabled: true

deploymentStrategy:
  type: Recreate

datasources:
 datasources.yaml:
   apiVersion: 1
   datasources:
   - name: Prometheus
     type: prometheus
     url: http://prometheus-operated.prometheus:9090
     access: proxy
     isDefault: true
   - name: Loki
     type: loki
     url: http://loki-gateway.loki
     access: proxy
     isDefault: false
     editable: true


dashboardProviders:
 dashboardproviders.yaml:
   apiVersion: 1
   providers:
   - name: 'default'
     orgId: 1
     folder: ''
     type: file
     disableDeletion: false
     editable: true
     options:
       path: /var/lib/grafana/dashboards/default

dashboards:
  default:
    # https://grafana.com/grafana/dashboards/1860-node-exporter-full/
    prometheus-nodes:
      gnetId: 1860
      revision: 36
      datasource: Prometheus
      editable: true
    # https://grafana.com/grafana/dashboards/15141-kubernetes-service-logs/
    loki-logs:
      gnetId: 15141
      revision: 1
      datasource: Loki
      editable: true
    # https://grafana.com/grafana/dashboards/15758-kubernetes-views-namespaces/
    kubernetes-views-namespaces:
      gnetId: 15758
      revision: 34
      datasource: Prometheus
      editable: true
    # https://grafana.com/grafana/dashboards/7587-prometheus-blackbox-exporter/
    blackbox-exporter:
      gnetId: 7587
      revision: 3
      datasource: Prometheus
      editable: true
    # https://grafana.com/grafana/dashboards/2-prometheus-stats/
    prometheus-stats:
      gnetId: 2
      revision: 2
      datasource: Prometheus
      editable: true
    # https://grafana.com/grafana/dashboards/13995-policyreport-details/
    kyverno:
      gnetId: 13995
      revision: 5
      datasource: Prometheus
      editable: true
    # https://grafana.com/grafana/dashboards/17346-traefik-official-standalone-dashboard/
    traefik-official:
      gnetId: 17346
      revision: 9
      datasource: Prometheus
      editable: true
    # https://github.com/cloudnative-pg/grafana-dashboards/tree/main/charts/cluster
    cloudnativepg:
      url: https://raw.githubusercontent.com/cloudnative-pg/grafana-dashboards/main/charts/cluster/grafana-dashboard.json
      datasource: Prometheus
      editable: true
    # https://grafana.com/grafana/dashboards/16337-trivy-operator-vulnerabilities/
    trivy-operator-vulnerabilities:
      gnetId: 16337
      revision: 13
      datasource: Prometheus
      editable: true
    # https://grafana.com/grafana/dashboards/13922-certificates-expiration-x509-certificate-exporter/
    x509-certificate-exporter:
      gnetId: 13922
      revision: 4
      datasource: Prometheus
      editable: true

# downloadDashboards:
#   env:
#     HTTP_PROXY: http://proxy:3128
#     HTTPS_PROXY: http://proxy:3128
