persistence:
  enabled: true

sidecar:
  dashboards:
    enabled: true
  datasources:
    enabled: true

deploymentStrategy:
  type: Recreate

datasources:
 datasources.yaml:
   apiVersion: 1
   datasources:
   - name: Prometheus
     type: prometheus
     url: http://prometheus-operated.prometheus:9090
     access: proxy
     isDefault: true
   - name: Loki
     type: loki
     url: http://loki-gateway.loki
     access: proxy
     isDefault: false
     editable: true


dashboardProviders:
 dashboardproviders.yaml:
   apiVersion: 1
   providers:
   - name: 'default'
     orgId: 1
     folder: ''
     type: file
     disableDeletion: false
     editable: true
     options:
       path: /var/lib/grafana/dashboards/default

dashboards:
  default:
    # https://grafana.com/grafana/dashboards/2-prometheus-stats/
    prometheus-stats:
      gnetId: 2
      revision: 2
      datasource: Prometheus
      editable: true
    # https://grafana.com/grafana/dashboards/15141-kubernetes-service-logs/
    loki-logs:
      gnetId: 15141
      revision: 1
      datasource: Loki
      editable: true
    # https://grafana.com/grafana/dashboards/7587-prometheus-blackbox-exporter/
    blackbox-exporter:
      gnetId: 7587
      revision: 3
      datasource: Prometheus
      editable: true
    # https://grafana.com/grafana/dashboards/13995-policyreport-details/
    kyverno:
      gnetId: 13995
      revision: 5
      datasource: Prometheus
      editable: true

# downloadDashboards:
#   env:
#     HTTP_PROXY: http://proxy:3128
#     HTTPS_PROXY: http://proxy:3128
