version: '3.5'

services:

  gogs:
    container_name: gogs
    image: gogs/gogs:0.11
    ports:
      - "10022:22"
    labels:
      - "traefik.enable=true"
      - "traefik.port=3000"
      - "traefik.frontend.rule=Host:gogs.${HOST_HOSTNAME}"
    volumes:
      - gogs-data:/data
      - ./backup:/backup
    restart: always

volumes:
  gogs-data:
    name: gogs-data

networks:
  default:
    external:
      name: webgateway
