version: '3.5'

services:

  gogs:
    container_name: gogs
    image: mborne/gogs:0.11
    build: .
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.gogs.rule=Host(`gogs.${HOST_HOSTNAME}`)"
    volumes:
      - gogs-data:/data
      - backup:/backup
    restart: unless-stopped

volumes:
  backup:
    name: backup
  gogs-data:
    name: gogs-data

networks:
  default:
    external:
      name: devbox
