controller:
  ingressClass: nginx

  metrics:
    enabled: true
    service:
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "10254"
        prometheus.io/path: "/metrics"
        prometheus.io/scheme: "http"
