version: '3.8'
services:
  redis:
    image: redis:6.2-alpine
    container_name: redis
    ports:
      - '${DEVBOX_PORT_PREFIX}6379:6379'
    command: redis-server --save 20 1 --loglevel warning --requirepass ${REDIS_PASSWORD}
    volumes: 
      - redis-data:/data
    restart: unless-stopped

volumes:
  redis-data:
    name: redis-data

networks:
  default:
    name: devbox
    external: true
